### ISSUE TITLE
disabled identity triggers service inventory timeout on startup

### ISSUE THREAD

**Issue by qrkourier** [openziti/desktop-edge-ui#4]
When I start the app I always get a notification like "all of the services for {identity} have timed out", but that identity is disabled and so I didn't expect the app to try to inventory available services at all.

EDIT: add app version: ZitiDesktopEdge@3.0.0

**Comment by JeremyTellier** [comment]
Fixed in Commit c35fc04

**Comment by qrkourier** [comment]
After pulling branch main and npm install && npm start I see all seven identities, but now I'm not sure which version I'm on because I still see v3.0.0 so maybe that value isn't updating.
